name: aceena
channels:
   - conda-forge
dependencies:
   - python=3.6
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - metpy
   - siphon
   - xarray
   - scipy
   - boto
   - basemap
   - basemap-data-hires
   - boto3
   - urllib3
